### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by kolyshkin** [tim-actions/get-pr-commits#13]
In the light of recent fixes (#7 and #11), can we please have a new tagged release, say v1.3.0? Otherwise the users will still be getting those deprecation warnings about Node 12 and set-output.

**Comment by kolyshkin** [comment]
Also, once done, issues #8 and #9 can be closed.

**Comment by kolyshkin** [comment]
@Tim-Zhang 🙏🏻

**Comment by kolyshkin** [comment]
@Tim-Zhang very please?

**Comment by Tim-Zhang** [comment]
@kolyshkin I've just released the new version: https://github.com/tim-actions/get-pr-commits/releases/tag/v1.3.0
