### ISSUE TITLE
Please make/tag a release

### ISSUE THREAD

**Issue by kolyshkin** [tim-actions/get-pr-commits#3]
Currently, https://github.com/tim-actions/commit-message-checker-with-regex/ have to use this action without a tag, i.e.

```
        uses: tim-actions/get-pr-commits@master
```

It would be much nicer to make a tag/release (say `v1.0.1` or `v1.1.0`) and refer to it elsewhere.

PS while at it, can you please enable "Issues" for the https://github.com/tim-actions/commit-message-checker-with-regex/ repo -- there is a problem with tags in there and I can't file an issue :(

**Comment by Tim-Zhang** [comment]
@kolyshkin I have released the version v1.1.0 and the issue of https://github.com/tim-actions/commit-message-checker-with-regex has been enabled.
