### ISSUE TITLE
Node 12 Actions are deprecated

### ISSUE THREAD

**Issue by gesellix** [tim-actions/get-pr-commits#8]
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

The action should be upgraded to Node 16.

**Comment by kolyshkin** [comment]
Should be fixed by https://github.com/tim-actions/get-pr-commits/pull/11

**Comment by dfarrell07** [comment]
This can be closed IMHO. :heavy_check_mark:

**Comment by Tim-Zhang** [comment]
Thanks @gesellix @kolyshkin @dfarrell07 , I've just released the version 1.3.0, so I think this issue could be closed.
