### ISSUE TITLE
Set-output command is deprecated

### ISSUE THREAD

**Issue by gesellix** [tim-actions/get-pr-commits#9]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The action should use [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).

**Comment by kolyshkin** [comment]
Should be fixed by https://github.com/tim-actions/get-pr-commits/pull/7

**Comment by kolyshkin** [comment]
@Tim-Zhang as per my previous comment, this can be closed. Yet we need a formal tagged release.

**Comment by Tim-Zhang** [comment]
released and close

**Comment by kolyshkin** [comment]
Indeed it is :(

From https://github.com/opencontainers/runc/actions/runs/5159039670/jobs/9293449992:

```
Run tim-actions/get-pr-commits@v1.3.0
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

@madelinevdp can you please open a PR, or an issue?

**Comment by kolyshkin** [comment]
Trying to fix this with https://github.com/tim-actions/get-pr-commits/pull/18
